### PR TITLE
ISSUE-46: OCR language and better single Image sequencing

### PR DESCRIPTION
**Pull request by DiegoPino**
See [ #46](https://github.com/esmero/strawberry_runners/issues/46)

@patdunlavey this brings some changes to your open pull.

To test please use the following Docker containers:

`esmero/php-8.0-fpm:1.0.0-dev-multiarch` (for xdebug)
` esmero/php-8.0-fpm:1.0.0-multiarch` (for production)

And also please use https://github.com/esmero/strawberryfield/pull/218 (check if you feel that is OK for merging, if so we can merge right now) and go for 1.0.0 in general maybe before testing

docker exec -ti esmero-php bash -c "composer require strawberryfield/strawberryfield:1.0.0.x-dev strawberryfield/format_strawberryfield:1.0.0.x-dev strawberryfield/webform_strawberryfield:1.0.0.x-dev archipelago/ami:0.4.0.x-dev strawberryfield/strawberry_runners:0.4.0.x-dev"

Since new containers have 2x Tesseracts you want to change your settings on the OCR and the JSON Pager Post processors. Just noticed another tiny thing that needs removal and will update tomorrow more. But this works already.

### CODE REVIEW

**Comment by DiegoPino** [comment]
Will update screenshots/instructions tomorrow morning but did not wanted to leave this here without making a pull (sorry for the delay)

**Comment by DiegoPino** [comment]
Pager Config
image

OCR config
image


Strawberry Flavor config, notice that we are getting also for Creative Work Series (for anything really) the sequence ID relative to the parent Node. 

image

**Comment by patdunlavey** [comment]
@DiegoPino I apologize for taking so long to get back to working on this! I am finding some issues that I hope are due to mistakes on my part. 

First, I have ocr running successfully for an object (type "Book") that has multiple image files (I can see the ocr/hocr data in solr), and am displaying the pages successfully using the book viewer. However book viewer search is not finding anything. I suspect that I haven't adapted my "IIIF Presentation API 3.0 Manifest" template correctly to tell IABookViewer where to get the hocr data. If you have this use case working, can you share your template (or the relevant part), and if not, offer any advice on what to try?

Second, I've tested two pdfalto with embedded text pdf files, and it's successfully generating ocr (yay!!!!). However, for one of my test pdf files, though the ocr is successfully completing, the solr indexing of that resulting ocr is failing, complaining of a "possible analysis error". It worked fine for another embedded text pdf. Smells like character encoding. Have you seen this, and/or have any theories about how to make it work? I can attach a sample of the ocr output if that helps.

**Comment by DiegoPino** [comment]
@patdunlavey all good.The Search / results goes into other pulls, that is in two other modules (format_strawberryfield + strawberryfield), this one is the key,  getting the Data that the other two need to work on. Merging this won't hurt, the opposite, can't move on with the others without this.

But:
1.- I need to see that failed PDF. OCR highlight is very picky about the format of the OCR. Maybe the AltoToMini OCR is skipping some tag or leaving one empty. Can you Slack/share/it/with/me? Also, yes, char encoding might be an issue. Please share it!

Also:

Can you add an old configuration keys hook update (delete those old configs) hook once we figure out the PDF that is failing?

Thanks!

**Comment by patdunlavey** [comment]
Thanks @DiegoPino. As it happens the PDF that failed to index is the Born-Digital employee handbook which has non-disclosure language in it and I can't share it with you! It took me a while but I found another pdf that succeeds to OCR but fails to index, and I'll send the link to you in slack.

Pending your investigations into that, I agree, let's get this merged and move on to the other PRs that depend on this!

**Comment by patdunlavey** [comment]
Re. the update hook, yes I can write it. This is to add
Screenshot from 2022-05-04 11-14-47
...and...
Screenshot from 2022-05-04 11-15-05
?

**Comment by DiegoPino** [comment]
Yes and the schema YML I committed should good as a reference of what should stay (pretty sure I made it 1:1 with the current config). So a diff (remove old ones) add the new ones should be enough (don’t forget about the language settings too!)

**Comment by patdunlavey** [comment]
@DiegoPino I seem to have gotten turned around in the git-verse. I wrote an update hook and [committed](https://github.com/Born-Digital-US/strawberry_runners/commit/7a533e98bf6433e33c6c1d23adaaa2fd24a75995) it to [my ISSUE-46-OCR branch](https://github.com/Born-Digital-US/strawberry_runners/tree/ISSUE-46-OCR), but then realized that this is an MR from your branch into mine! I'm thinking I should accept your merge request, and then make an MR back to [esmero:ISSUE-46-OCR-lang](https://github.com/esmero/strawberry_runners/tree/ISSUE-46-OCR-lang)?

**Comment by DiegoPino** [comment]
@patdunlavey I checked with the PDF you shared with me and I had no issues indexing or searching on Solr Highlight 0.5.0 but yes on 0.7.1. The problem was a mismatch on the Alto to MiniOCR code (v/s the HOCR to miniOCR) where empty <w> tags were not removed, e.g like this

```XML
          <l>
                <w x=".150 .919 .112 .010">commonmedia.com</w>
                <w x=".269 .919 .000 .015"/>
                <w x=".269 .919 .008 .010">//</w>
                <w x=".283 .919 .015 .010">84</w>
````
New code in https://github.com/Born-Digital-US/strawberry_runners/pull/1/commits/c13dc2c8678ddd3006fc784624527560027a886a fixes this. Can you please test? Do I need to merge something? I kinda need this to get the Search working for Creative Work Series soon. Thanks!

**Comment by DiegoPino** [comment]
Also: when you merge into your branch do not squash. That way all commits are preserved and we can track back what went wrong in the future (bc always something goes wrong in the future). Thanks

**Comment by patdunlavey** [comment]
I cherry-picked your [c13dc2c](https://github.com/Born-Digital-US/strawberry_runners/commit/c13dc2c8678ddd3006fc784624527560027a886a) fix and it appears to work as advertised! Honestly, I'm a little lost in this git patch. I'm going to go ahead and merge and see where we are once that's done.

**Comment by patdunlavey** [comment]
I cherry-picked your [c13dc2c](https://github.com/Born-Digital-US/strawberry_runners/commit/c13dc2c8678ddd3006fc784624527560027a886a) fix and it appears to work as advertised! Honestly, I'm a little lost in this git patch. I'm going to go ahead and merge and see where we are once that's done.

**Comment by DiegoPino** [comment]
Thanks a lot @patdunlavey I missed you!

**Pull request merged**
